# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: raptor-os
description: Victory Build.
base-image: ghcr.io/ublue-os/bazzite
image-version: latest
modules:
  - type: rpm-ostree
    install:
      - firefox
      - fastfetch
      - plasma-systemmonitor
      - libreoffice
      - thunderbird
      - kdenlive
      - gimp
      - bottles
      - discord
      - heroic-games-launcher
      - gamemode
      - goverlay
      - zenity
      - vscodium
      - git
      - gh
      - nodejs
      - python3
      - python3-pip
      - gcc
      - make
  - type: script
    scripts:
      - raptor-hud.sh
  - type: systemd
    system:
      enabled:
        - raptor-firstboot.service
