name: build-raptor
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build and Push Image
        uses: blue-build/github-action@v1.6.1
        with:
          recipe: recipe.yml
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          cli_version: latest
          build_opts: --no-sign
  iso:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.4.0
        id: build
        with:
          image_name: raptor-os
          image_repo: ghcr.io/cerberus9-dev
          image_tag: latest
          version: 41
          variant: Kinoite
          iso_name: raptor-os.iso
      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v7
        with:
          name: raptor-os-iso
          retention-days: 5
          path: /home/runner/work/Raptor-OS/Raptor-OS/raptor-os.iso
      - name: Create Tag
        run: |
          git tag v1.0 --force
          git push origin v1.0 --force
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v1.0
          name: Raptor OS v1.0
          body: Latest build of Raptor OS
          make_latest: true
          files: /home/runner/work/Raptor-OS/Raptor-OS/raptor-os.iso
        env:
          GITHUB_TOKEN: ${{ github.token }}
