name: build-raptor-os
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Raptor OS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Raptor Image
        uses: blue-build/github-action@v1
        with:
          recipe: recipes/recipe.yml
          registry_token: ${{ github.token }}
          maximize_build_space: true
